kind: PersistentVolume
apiVersion: v1
metadata:
  name: highscore-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"